site_name: ActiveTigger Documentation
nav:
  - Home: index.md
  - First steps: 
    - Quickstart: quickstart/quickstart.md
    - Use cases: quickstart/usecases.md
    - Get Access: access.md
    - Environemental impact: quickstart/environment.md
  - Showcase uses: showcase/usecases.md
  - Functionalities: documentation.md
  - Software: 
    - Archiecture: software.md
    - Contributors: contributors.md
  - FAQ: faq.md

markdown_extensions:
  - footnotes
  - admonition

theme: readthedocs