site_name: ActiveTigger Documentation
nav:
  - Home: index.md
  - First steps: 
    - Quickstart: quickstart/quickstart.md
    - Use cases: quickstart/usecases.md
    - Get Access: access.md
    - Environemental impact: quickstart/environment.md
  - Showcase: 
    - Real uses: showcase/usecases.md
  - Functionalities:
    - General organisation: functionalities/organisation.md
  - Software: 
    - Architecture: software.md
    - Contributors: contributors.md
  - FAQ: 
    - Main qestions: faq/faq.md

markdown_extensions:
  - footnotes
  - admonition

theme: readthedocs