site_name: ActiveTigger Documentation
nav:
  - Home: index.md
  - Get started:
      - Quickstart: getstarted/quickstart.md
      - Main workflows: getstarted/workflows.md
      - How people use it: getstarted/howpeopleuseit.md
      - Existing tutorials and videos: getstarted/tutorials.md
  - Technicalities:
      - Prepare your dataset: technicalities/prepare-your-dataset.md
      - Install & access: technicalities/access.md
  - Functionalities:
      - Project Creation: functionalities/project-creation.md
      - Codebook Page: functionalities/codebook.md
      - Explore Page: functionalities/explore.md
      - Annotate Page: functionalities/annotate.md
      - Model Page: functionalities/model.md
      - Export Page: functionalities/export.md
      - Generative Page: functionalities/generative.md
      - Settings Page: functionalities/settings.md
      - Account and Users: functionalities/account-and-users.md
      - Monitoring: functionalities/monitoring.md

  - Conceptualizing:
      - General concepts: conceptualizing/general.md
      - Glossary: conceptualizing/glossary.md
  - Software:
      - Architecture: software/architecture.md
      - Roadmap: software/roadmap.md
      - Contributors: software/contributors.md
      - Doc semiology: software/semiology.md
  - FAQ:
      - Environmental impact: faq/environment.md
      - Main questions: faq/faq.md

markdown_extensions:
  - footnotes
  - admonition

theme: readthedocs

extra_css:
  - style.css
